"""add_product_sales_table

Revision ID: 628272f8e4d5
Revises: 327ef1d55c07
Create Date: 2026-02-19 17:17:07.398624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628272f8e4d5'
down_revision = '327ef1d55c07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_sales_company_id'), 'product_sales', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_sales_id'), 'product_sales', ['id'], unique=False)
    op.create_index(op.f('ix_product_sales_product_id'), 'product_sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_sales_sale_date'), 'product_sales', ['sale_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_sales_sale_date'), table_name='product_sales')
    op.drop_index(op.f('ix_product_sales_product_id'), table_name='product_sales')
    op.drop_index(op.f('ix_product_sales_id'), table_name='product_sales')
    op.drop_index(op.f('ix_product_sales_company_id'), table_name='product_sales')
    op.drop_table('product_sales')
    # ### end Alembic commands ###
