"""add_quotations_module

Revision ID: d157742e9f9c
Revises: 7b9c4f2e8d3a
Create Date: 2026-04-16 22:05:01.681484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd157742e9f9c'
down_revision = '7b9c4f2e8d3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('BORRADOR', 'ENVIADA', 'APROBADA', name='quotationstatus'), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_nit', sa.String(), nullable=True),
    sa.Column('client_contact', sa.String(), nullable=True),
    sa.Column('client_phone', sa.String(), nullable=True),
    sa.Column('client_email', sa.String(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('payment_conditions', sa.Text(), nullable=True),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_company_id'), 'quotations', ['company_id'], unique=False)
    op.create_index(op.f('ix_quotations_id'), 'quotations', ['id'], unique=False)
    op.create_index(op.f('ix_quotations_number'), 'quotations', ['number'], unique=False)
    op.create_table('quotation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('has_sizes', sa.Boolean(), nullable=False),
    sa.Column('sizes_breakdown', sa.JSON(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_items_id'), 'quotation_items', ['id'], unique=False)
    op.create_index(op.f('ix_quotation_items_product_id'), 'quotation_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_quotation_items_quotation_id'), 'quotation_items', ['quotation_id'], unique=False)
    op.add_column('products', sa.Column('has_sizes', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('products', sa.Column('available_sizes', sa.JSON(), nullable=True))
    op.alter_column('project_material_purchases', 'unit_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.add_column('projects', sa.Column('quotation_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_projects_quotation_id'), 'projects', ['quotation_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'quotations', ['quotation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_quotation_id'), table_name='projects')
    op.drop_column('projects', 'quotation_id')
    op.alter_column('project_material_purchases', 'unit_cost',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('products', 'available_sizes')
    op.drop_column('products', 'has_sizes')
    op.create_table('project_template_stages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stage_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stage_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('has_operational_cost', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('cost_per_unit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], name=op.f('project_template_stages_stage_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['project_templates.id'], name=op.f('project_template_stages_template_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_template_stages_pkey')),
    sa.UniqueConstraint('template_id', 'stage_id', name=op.f('uq_template_stage'))
    )
    op.create_index(op.f('ix_project_template_stages_template_id'), 'project_template_stages', ['template_id'], unique=False)
    op.create_index(op.f('ix_project_template_stages_stage_id'), 'project_template_stages', ['stage_id'], unique=False)
    op.create_index(op.f('ix_project_template_stages_id'), 'project_template_stages', ['id'], unique=False)
    op.create_table('project_template_stage_dependencies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('template_stage_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('depends_on_template_stage_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['depends_on_template_stage_id'], ['project_template_stages.id'], name=op.f('project_template_stage_depend_depends_on_template_stage_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['project_templates.id'], name=op.f('project_template_stage_dependencies_template_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_stage_id'], ['project_template_stages.id'], name=op.f('project_template_stage_dependencies_template_stage_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_template_stage_dependencies_pkey')),
    sa.UniqueConstraint('template_stage_id', 'depends_on_template_stage_id', name=op.f('uq_template_dependency'))
    )
    op.create_index(op.f('ix_project_template_stage_dependencies_template_id'), 'project_template_stage_dependencies', ['template_id'], unique=False)
    op.create_index(op.f('ix_project_template_stage_dependencies_id'), 'project_template_stage_dependencies', ['id'], unique=False)
    op.drop_index(op.f('ix_quotation_items_quotation_id'), table_name='quotation_items')
    op.drop_index(op.f('ix_quotation_items_product_id'), table_name='quotation_items')
    op.drop_index(op.f('ix_quotation_items_id'), table_name='quotation_items')
    op.drop_table('quotation_items')
    op.drop_index(op.f('ix_quotations_number'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_company_id'), table_name='quotations')
    op.drop_table('quotations')
    # ### end Alembic commands ###
