"""add_adds_to_inventory_to_projects

Revision ID: 327ef1d55c07
Revises: e3dc9dc044e6
Create Date: 2026-02-19 16:58:06.365547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '327ef1d55c07'
down_revision = 'e3dc9dc044e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.create_index(op.f('ix_project_stage_dependencies_depends_on_stage_id'), 'project_stage_dependencies', ['depends_on_stage_id'], unique=False)
    op.create_index(op.f('ix_project_stage_dependencies_id'), 'project_stage_dependencies', ['id'], unique=False)
    
    # Add column with default value first
    op.add_column('projects', sa.Column('adds_to_inventory', sa.Boolean(), nullable=True, server_default=sa.false()))
    # Update existing rows
    op.execute('UPDATE projects SET adds_to_inventory = false WHERE adds_to_inventory IS NULL')
    # Make column not nullable
    op.alter_column('projects', 'adds_to_inventory', nullable=False)
    
    op.create_index(op.f('ix_stage_event_log_id'), 'stage_event_log', ['id'], unique=False)
    op.create_index(op.f('ix_stage_event_log_user_id'), 'stage_event_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_event_log_user_id'), table_name='stage_event_log')
    op.drop_index(op.f('ix_stage_event_log_id'), table_name='stage_event_log')
    op.drop_column('projects', 'adds_to_inventory')
    op.drop_index(op.f('ix_project_stage_dependencies_id'), table_name='project_stage_dependencies')
    op.drop_index(op.f('ix_project_stage_dependencies_depends_on_stage_id'), table_name='project_stage_dependencies')
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_stage_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('notifications_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_stage_id'], ['project_stages.id'], name=op.f('notifications_project_stage_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    # ### end Alembic commands ###
