"""Initial migration

Revision ID: 798eb9afb0f7
Revises: 
Create Date: 2026-02-10 02:24:44.806215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798eb9afb0f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_company_id'), 'materials', ['company_id'], unique=False)
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('total_qty', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('final_deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_company_id'), 'projects', ['company_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stages_company_id'), 'stages', ['company_id'], unique=False)
    op.create_index(op.f('ix_stages_id'), 'stages', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'COMPANY_ADMIN', 'STAGE_WORKER', name='userrole'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('financial_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'COST', name='financialeventtype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_events_id'), 'financial_events', ['id'], unique=False)
    op.create_index(op.f('ix_financial_events_project_id'), 'financial_events', ['project_id'], unique=False)
    op.create_table('product_bom_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty_per_unit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_bom_items_id'), 'product_bom_items', ['id'], unique=False)
    op.create_index(op.f('ix_product_bom_items_material_id'), 'product_bom_items', ['material_id'], unique=False)
    op.create_index(op.f('ix_product_bom_items_product_id'), 'product_bom_items', ['product_id'], unique=False)
    op.create_table('project_material_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty_per_unit', sa.Float(), nullable=False),
    sa.Column('qty_total', sa.Float(), nullable=False),
    sa.Column('qty_available', sa.Float(), nullable=False),
    sa.Column('qty_to_buy', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_material_requirements_id'), 'project_material_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_project_material_requirements_material_id'), 'project_material_requirements', ['material_id'], unique=False)
    op.create_index(op.f('ix_project_material_requirements_project_id'), 'project_material_requirements', ['project_id'], unique=False)
    op.create_table('project_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('BLOCKED', 'READY', 'IN_PROGRESS', 'DONE', 'SKIPPED', name='stagestatus'), nullable=False),
    sa.Column('qty_required', sa.Integer(), nullable=False),
    sa.Column('qty_done', sa.Integer(), nullable=False),
    sa.Column('planned_due_date', sa.Date(), nullable=False),
    sa.Column('actual_ready_at', sa.DateTime(), nullable=True),
    sa.Column('actual_started_at', sa.DateTime(), nullable=True),
    sa.Column('actual_done_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_stages_id'), 'project_stages', ['id'], unique=False)
    op.create_index(op.f('ix_project_stages_project_id'), 'project_stages', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_stages_stage_id'), 'project_stages', ['stage_id'], unique=False)
    op.create_table('stage_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_stage_id', sa.Integer(), nullable=False),
    sa.Column('to_stage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['to_stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_edges_from_stage_id'), 'stage_edges', ['from_stage_id'], unique=False)
    op.create_index(op.f('ix_stage_edges_id'), 'stage_edges', ['id'], unique=False)
    op.create_index(op.f('ix_stage_edges_to_stage_id'), 'stage_edges', ['to_stage_id'], unique=False)
    op.create_table('user_stage_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stage_access_id'), 'user_stage_access', ['id'], unique=False)
    op.create_index(op.f('ix_user_stage_access_stage_id'), 'user_stage_access', ['stage_id'], unique=False)
    op.create_index(op.f('ix_user_stage_access_user_id'), 'user_stage_access', ['user_id'], unique=False)
    op.create_table('time_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_stage_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_stage_id'], ['project_stages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_logs_id'), 'time_logs', ['id'], unique=False)
    op.create_index(op.f('ix_time_logs_project_stage_id'), 'time_logs', ['project_stage_id'], unique=False)
    op.create_index(op.f('ix_time_logs_user_id'), 'time_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_logs_user_id'), table_name='time_logs')
    op.drop_index(op.f('ix_time_logs_project_stage_id'), table_name='time_logs')
    op.drop_index(op.f('ix_time_logs_id'), table_name='time_logs')
    op.drop_table('time_logs')
    op.drop_index(op.f('ix_user_stage_access_user_id'), table_name='user_stage_access')
    op.drop_index(op.f('ix_user_stage_access_stage_id'), table_name='user_stage_access')
    op.drop_index(op.f('ix_user_stage_access_id'), table_name='user_stage_access')
    op.drop_table('user_stage_access')
    op.drop_index(op.f('ix_stage_edges_to_stage_id'), table_name='stage_edges')
    op.drop_index(op.f('ix_stage_edges_id'), table_name='stage_edges')
    op.drop_index(op.f('ix_stage_edges_from_stage_id'), table_name='stage_edges')
    op.drop_table('stage_edges')
    op.drop_index(op.f('ix_project_stages_stage_id'), table_name='project_stages')
    op.drop_index(op.f('ix_project_stages_project_id'), table_name='project_stages')
    op.drop_index(op.f('ix_project_stages_id'), table_name='project_stages')
    op.drop_table('project_stages')
    op.drop_index(op.f('ix_project_material_requirements_project_id'), table_name='project_material_requirements')
    op.drop_index(op.f('ix_project_material_requirements_material_id'), table_name='project_material_requirements')
    op.drop_index(op.f('ix_project_material_requirements_id'), table_name='project_material_requirements')
    op.drop_table('project_material_requirements')
    op.drop_index(op.f('ix_product_bom_items_product_id'), table_name='product_bom_items')
    op.drop_index(op.f('ix_product_bom_items_material_id'), table_name='product_bom_items')
    op.drop_index(op.f('ix_product_bom_items_id'), table_name='product_bom_items')
    op.drop_table('product_bom_items')
    op.drop_index(op.f('ix_financial_events_project_id'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_id'), table_name='financial_events')
    op.drop_table('financial_events')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stages_id'), table_name='stages')
    op.drop_index(op.f('ix_stages_company_id'), table_name='stages')
    op.drop_table('stages')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_company_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_company_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
