"""add_project_material_purchases_table

Revision ID: 8bcb192c9bf5
Revises: 313146aeb121
Create Date: 2026-02-15 23:01:08.774106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bcb192c9bf5'
down_revision = '313146aeb121'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_material_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_stage_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('quantity_purchased', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['project_stage_id'], ['project_stages.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_material_purchases_id'), 'project_material_purchases', ['id'], unique=False)
    op.create_index(op.f('ix_project_material_purchases_material_id'), 'project_material_purchases', ['material_id'], unique=False)
    op.create_index(op.f('ix_project_material_purchases_project_id'), 'project_material_purchases', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_material_purchases_project_stage_id'), 'project_material_purchases', ['project_stage_id'], unique=False)
    op.create_index(op.f('ix_project_material_purchases_supplier_id'), 'project_material_purchases', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_material_purchases_supplier_id'), table_name='project_material_purchases')
    op.drop_index(op.f('ix_project_material_purchases_project_stage_id'), table_name='project_material_purchases')
    op.drop_index(op.f('ix_project_material_purchases_project_id'), table_name='project_material_purchases')
    op.drop_index(op.f('ix_project_material_purchases_material_id'), table_name='project_material_purchases')
    op.drop_index(op.f('ix_project_material_purchases_id'), table_name='project_material_purchases')
    op.drop_table('project_material_purchases')
    # ### end Alembic commands ###
