"""add_inventory_configuration_and_product_inventory

Revision ID: c694a2a31307
Revises: d3181b61be93
Create Date: 2026-02-15 18:51:18.509892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c694a2a31307'
down_revision = 'd3181b61be93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_available', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_inventory_company_id'), 'product_inventory', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_inventory_id'), 'product_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_product_inventory_product_id'), 'product_inventory', ['product_id'], unique=False)
    
    # Add columns as nullable first
    op.add_column('companies', sa.Column('track_raw_materials_inventory', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('track_finished_products_inventory', sa.Boolean(), nullable=True))
    
    # Set default values for existing companies
    op.execute("UPDATE companies SET track_raw_materials_inventory = TRUE WHERE track_raw_materials_inventory IS NULL")
    op.execute("UPDATE companies SET track_finished_products_inventory = FALSE WHERE track_finished_products_inventory IS NULL")
    
    # Make columns NOT NULL
    op.alter_column('companies', 'track_raw_materials_inventory', nullable=False)
    op.alter_column('companies', 'track_finished_products_inventory', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'track_finished_products_inventory')
    op.drop_column('companies', 'track_raw_materials_inventory')
    op.drop_index(op.f('ix_product_inventory_product_id'), table_name='product_inventory')
    op.drop_index(op.f('ix_product_inventory_id'), table_name='product_inventory')
    op.drop_index(op.f('ix_product_inventory_company_id'), table_name='product_inventory')
    op.drop_table('product_inventory')
    # ### end Alembic commands ###
