"""add_material_purchases_table

Revision ID: 313146aeb121
Revises: c694a2a31307
Create Date: 2026-02-15 19:32:53.878999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313146aeb121'
down_revision = 'c694a2a31307'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_purchases_company_id'), 'material_purchases', ['company_id'], unique=False)
    op.create_index(op.f('ix_material_purchases_id'), 'material_purchases', ['id'], unique=False)
    op.create_index(op.f('ix_material_purchases_material_id'), 'material_purchases', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_purchases_supplier_id'), 'material_purchases', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_purchases_supplier_id'), table_name='material_purchases')
    op.drop_index(op.f('ix_material_purchases_material_id'), table_name='material_purchases')
    op.drop_index(op.f('ix_material_purchases_id'), table_name='material_purchases')
    op.drop_index(op.f('ix_material_purchases_company_id'), table_name='material_purchases')
    op.drop_table('material_purchases')
    # ### end Alembic commands ###
