"""add_is_purchasing_stage_to_stage

Revision ID: d3181b61be93
Revises: 0d672ccfd3c6
Create Date: 2026-02-13 19:43:19.773392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3181b61be93'
down_revision = '0d672ccfd3c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_project_products_id'), 'project_products', ['id'], unique=False)
    
    # Add column as nullable first
    op.add_column('stages', sa.Column('is_purchasing_stage', sa.Boolean(), nullable=True))
    
    # Update existing rows to False
    op.execute("UPDATE stages SET is_purchasing_stage = FALSE WHERE is_purchasing_stage IS NULL")
    
    # Make it non-nullable
    op.alter_column('stages', 'is_purchasing_stage', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stages', 'is_purchasing_stage')
    op.drop_index(op.f('ix_project_products_id'), table_name='project_products')
    # ### end Alembic commands ###
